@root = http://127.0.0.1:3000/api/v1/media

@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzM2ZTIzYzljMWU5NjdmOWNlMGI5ODMiLCJlbWFpbCI6ImZhcmhhZEBnbWFpbC5jb20iLCJpYXQiOjE3MzE2NTAxMDksImV4cCI6MTczOTQyNjEwOX0.8krrYm5SnZJo7DzAtDgGI_Wp742OyeaTtBI00qFAhAk


### upload
# @name upload
POST {{root}}/
Authorization: {{authToken}}
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="photos"; filename="0c7ad0a8caf5fb7109eb737a4028375c.jpg"
Content-Type: image/jpeg

< /Users/nous/nebula/nihad_50/api/media/espresso200.png
--boundary123--


### get images 

# @name list
GET http://127.0.0.1:3000/md/0ac27c30-b9ce-4acd-ad68-a7f3d9e2eb00.jpeg