@root = http://localhost:3000/api/v1/users

@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzliN2YwMTBkMmM5YzI1OTk5NmRhZDAiLCJlbWFpbCI6ImpvaG4uZG9lQGpvaG4uZG9lIiwiaWF0IjoxNzM4MjQzODQyLCJleHAiOjE3Mzg4NDg2NDJ9.QJQTKZ4C2gjpU3LexQ1T0nIQgjHwnHjHW6RsrbufxwA


### my profile

# @name me
GET {{root}}/me
Content-Type: application/json
Authorization: {{authToken}}





### add address

# @name addAddress
POST {{root}}/me/address
Content-Type: application/json
Authorization: {{authToken}}

{
    "address": {
        "city": "Guneshli", 
        "street": "Ehmed Cavad 7D", 
        "apartment": "Dann", 
        "isPrimary": true
    }
}




### update address

@addressId=673f9a11a8acb3ca39aa81af
# @name updateAddress
PATCH {{root}}/me/address/{{addressId}}
Content-Type: application/json
Authorization: {{authToken}}

{
    "address": {
        "city": "Baku", 
        "street": "Ehmed Cavad 7D", 
        "apartment": "Romeo", 
        "isPrimary": true
    }
}





### delete address

@addressId=673f9a11a8acb3ca39aa81af
# @name deleteAddress
DELETE {{root}}/me/address/{{addressId}}
Content-Type: application/json
Authorization: {{authToken}}






### my comments 

# @name comments
GET {{root}}/comments
Content-Type: application/json
Authorization: {{authToken}}




### my orders 

# @name orders
GET {{root}}/orders
Content-Type: application/json
Authorization: {{authToken}}


