name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Restart application on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{secrets.EC2_USER}}@${{secrets.EC2_IP}} 'bash -s' <<'EOF'
          cd ./api && git pull origin main
          npm install
          pm2 reload api
          EOF
